# This file was generated by GoReleaser. DO NOT EDIT.
cask "onekeymap-cli" do
  name "onekeymap-cli"
  desc "Universal keymap configuration tool for VSCode, Zed, IntelliJ and more"
  homepage "https://github.com/xinnjie/homebrew-onekeymap"
  version "0.3.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "onekeymap-cli"
  bash_completion "completions/onekeymap-cli.bash"
  zsh_completion "completions/_onekeymap-cli"
  fish_completion "completions/onekeymap-cli.fish"

  on_macos do
    url "https://github.com/xinnjie/onekeymap-cli/releases/download/v#{version}/onekeymap-cli_Darwin_all.tar.gz"
    sha256 "a83b7e952a71962474fffbb7ab9600b1c3097f959ce9332915979e73ff284529"
  end

  on_linux do
    on_intel do
      url "https://github.com/xinnjie/onekeymap-cli/releases/download/v#{version}/onekeymap-cli_Linux_x86_64.tar.gz"
      sha256 "d3f4a983053775b7e509bd210148e7ad8539a54dffef4f9e271097b448515011"
    end
    on_arm do
      url "https://github.com/xinnjie/onekeymap-cli/releases/download/v#{version}/onekeymap-cli_Linux_arm64.tar.gz"
      sha256 "ea0ca9441690d1694e4372d57556b7cbec1a5fb6220891935efbd3d46e0835ec"
    end
  end

  # No zap stanza required
end
