# This file was generated by GoReleaser. DO NOT EDIT.
cask "onekeymap-cli" do
  name "onekeymap-cli"
  desc "Universal keymap configuration tool for VSCode, Zed, IntelliJ and more"
  homepage "https://github.com/xinnjie/homebrew-onekeymap"
  version "0.2.3"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "onekeymap-cli"
  bash_completion "completions/onekeymap-cli.bash"
  zsh_completion "completions/_onekeymap-cli"
  fish_completion "completions/onekeymap-cli.fish"

  on_macos do
    url "https://github.com/xinnjie/onekeymap-cli/releases/download/v#{version}/onekeymap-cli_Darwin_all.tar.gz"
    sha256 "4d8c85e5559328ad67044a81841d73dec68df8086ceb98d0491612be9d53a51a"
  end

  on_linux do
    on_intel do
      url "https://github.com/xinnjie/onekeymap-cli/releases/download/v#{version}/onekeymap-cli_Linux_x86_64.tar.gz"
      sha256 "65ef009e8d1179a4406689708c82964db28598f7378a14a9f088c7e95fc59c03"
    end
    on_arm do
      url "https://github.com/xinnjie/onekeymap-cli/releases/download/v#{version}/onekeymap-cli_Linux_arm64.tar.gz"
      sha256 "0e98e5078548bd42b0590f9cc03b61d02d9b40ad4671ca8650921596034e8bf8"
    end
  end

  # No zap stanza required
end
