# This file was generated by GoReleaser. DO NOT EDIT.
cask "onekeymap-cli" do
  name "onekeymap-cli"
  desc "Universal keymap configuration tool for VSCode, Zed, IntelliJ and more"
  homepage "https://github.com/xinnjie/homebrew-onekeymap"
  version "0.5.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "onekeymap-cli"
  bash_completion "completions/onekeymap-cli.bash"
  zsh_completion "completions/_onekeymap-cli"
  fish_completion "completions/onekeymap-cli.fish"

  on_macos do
    url "https://github.com/xinnjie/onekeymap-cli/releases/download/v#{version}/onekeymap-cli_Darwin_all.tar.gz"
    sha256 "fac4ab850e5fabf7c533eb23a76ddc7d3b7c21dc1b1af697c44ebd9e25082e0c"
  end

  on_linux do
    on_intel do
      url "https://github.com/xinnjie/onekeymap-cli/releases/download/v#{version}/onekeymap-cli_Linux_x86_64.tar.gz"
      sha256 "c9660574149bba4ed897c7bb44e00fa9008e169496130c078307892cd41f4813"
    end
    on_arm do
      url "https://github.com/xinnjie/onekeymap-cli/releases/download/v#{version}/onekeymap-cli_Linux_arm64.tar.gz"
      sha256 "eebf7504062d5041f8e2812832f8393580c3fefe66ef3e9397f470d07c312724"
    end
  end

  # No zap stanza required
end
